version:  '3.5'

services:
  service_nginx: nginx
    container_name: nginx_tno
    ports:
      - '443:443'
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - inception
    depends_on:
      - wordpress
    restart:
      - on-failure
    volumes:
      - wordpress:/var/www/wordpress
  service_mariadb:
    container_name: mariadb
    image: mariadb
    networks: 
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    restart:
      - on-failure
    expose:
      - "3306"
  service_wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
   networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - "9000"
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tnoulens/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tnoulens/data/mariadb
networks:
  inception:
    driver: bridge
