version : '3.5'
services :
  ftp:
    container_name: ftp
    image: ftp
    networks:
      - inception
    build:
      context: vsftpd
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21110:21100-21110

  jekyll:
    container_name: jekyll
    image:  jekyll
    networks:
      - inception
    build:
      context: jekyll
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - jekyll_vol:/my_jekyll_blogs/
    restart: on-failure
    ports:
      - 4000:4000

  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: ../requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ../.env
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_vol:/var/www/html/
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ../requirements/nginx
      dockerfile : Dockerfile
    env_file:
      - ../.env
    ports:
      - 443:443
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file:
      - ../.env
    volumes:
      - wordpress_vol:/var/www/html/
    networks:
      - inception
    build:
      context: ../requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tnoulens/data/wordpress
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tnoulens/data/mariadb
  jekyll_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tnoulens/data/jekyll

networks:
    inception:
      driver: bridge

